### ISSUE TITLE
无法在华为云帮助中心查询到ENI服务的相关信息

### ISSUE THREAD

**Issue by suxiaomeng1** [huaweicloudDocs/cce#2]
ENI（Elastic Network Interface，弹性网卡服务），无法在华为云帮助中心查询到ENI服务的相关信息，请重新评审ENI相关描述。

**Comment by yixiaoer2012** [comment]
ENI（Elastic Network Interface）是绑定私有网络内云服务器的一种弹性网络接口，可在多个云服务器间自由迁移。您可以在云服务器上绑定多个弹性网卡，实现高可用网络方案；也可以在弹性网卡上绑定多个内网 IP，实现单主机多 IP 部署。华为云目前未将ENI作为独立服务提供。
